spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-oyf-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-oyf-test    
      